title:             The Datalyst
email:             your-email@example.com
description:       A Blog about Data, Machine Learning, Deep Learning, Business Intelligence and Analytics
author:            Matheus Jacques
baseurl:           "/"
url:               "http://thedatalyst.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
