title:             The Datalyst
email:             your-email@example.com
description:       A Blog about Data, Machine Learning, Deep Learning, Business Intelligence and Analytics
author:            Matheus Jacques
baseurl:           "/"
url:               "http://thedatalyst.com"

# Social Profiles
twitter_username:  qisso
github_username:   jacquesmats
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Google Analytics
google_analytics: UA-134490041-1
